FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt requirements-test.txt ./
RUN pip install -r requirements.txt && pip install -r requirements-test.txt

COPY app/ ./app

ENV ENV=test
CMD ["pytest", "app/tests"]
